carousel_enabled: 
  default: true
  description: disabling this hides the homepage video carousel

carousel_videos: 
  type: list
  default: "youtube, RrdV3AgI00w|youtube, x1p5wcN24Pk|youtube, kzem8Jawino"
  description: Accepts either YouTube or directly hosted MP4s. <br/> Format each option like so&#58; <br/><ul> <li><b>YouTube&#58;</b> youtube, Jy5iHYArW9A <br/> <em>Where Jy5iHYArW9A is the youtube video ID, present in the URL after v= and before any &</em></li> <li><b>MP4&#58;</b> mp4, https://example.com/video.mp4</li></ul>
  
homepage_search_enabled: 
  default: true
  description: disabling this hides the homepage search callout

homepage_search_background: 
  default: "#ffffff"

feed_one_two_enabled:
  default: true
  description: disabling this hides the 2-column homepage feed

feed_one_title:
  default: General
  description: custom title

feed_one_category_slug:
  default: /c/general
  description: source of feed content, /c/category-name for categories or /tags/tag-name for tags

feed_two_title:
  default: Site Feedback
  description: custom title

feed_two_category_slug:
  default: /c/site-feedback
  description: source of feed content, /c/category-name for categories or /tags/tag-name for tags

feed_three_enabled: 
   default: true
   description: disabling this hides the 3-column homepage feed

feed_three_title:
  default: Meet Our Members
  description: custom title

feed_thee_category_id:
  default: 1
  description: ID of category that feeds this feature

feed_three_topics_order:
  default: ascending
  type: enum
  choices: 
    - ascending
    - descending
svg_icons: 
  default: 'chevron-left|chevron-right|comments|heart|lock'
  type: list
  description: Additional FontAwesome 5 icons used in this theme
